### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by A1337CBS** [trendmicro/ais#10]
Hi, 

I am trying to install this module on Ubuntu 19 using pybombs, there is some problem with finding the correct python version which I was able to bypass but now I am getting an error regarding this file, any ideas or how I can get the file manually?

`[ 19%] Built target gnuradio-AISTX
Scanning dependencies of target test-AISTX
[ 23%] Building CXX object lib/CMakeFiles/test-AISTX.dir/test_AISTX.cc.o
[ 28%] Building CXX object lib/CMakeFiles/test-AISTX.dir/qa_AISTX.cc.o
[ 33%] Linking CXX executable test-AISTX
[ 33%] Built target test-AISTX
make[2]: *** No rule to make target 'swig/AISTX_swig.py', needed by 'swig/AISTX_swig.pyc'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:242: swig/CMakeFiles/pygen_swig_7d327.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package gr-aistx:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package gr-aistx. Aborting.
`

**Comment by embyte0** [comment]
Hi,

saying that I never used `pybombs` in installing this code, others have reported a small issue related to new naming conventions used in recent libraries. You may wanna check here: https://github.com/trendmicro/ais/issues/9

Cheers

**Comment by A1337CBS** [comment]
Hi,

I used the code provided in #9 and then applied a hack to solve the other issue I was getting, it seems to work, as for the AIS receiver, if I try to build it in Gnuradio what should I keep in mind or should I just follow the latest AIS technical standard to build the receiver?

Thanks

**Comment by embyte0** [comment]
Hi,

if you look online you will find several AIS receivers developed and provided by different 3rd parties for your convenience. Some are closed-source while other are open, including a Gnuradio implementation.

Good luck! :)
