### ISSUE TITLE
Single shot transmission or how to stop endless loop

### ISSUE THREAD

**Issue by Mictronics** [trendmicro/ais#16]
I'm using your project as base for an AIS simulator. Implemented some code from another fork, so I can change sentence on the fly.
However, the top_block is running in endless loop, repeating transmission of a sentence. The build_frame block seems to have a "Repeat" option but obviously without effect. Repetition speed seems to be limited only be a delay at the end of "work" function in build_frame implementation.

So, how can I stop endless repetition of a sentence and create a single shot transmission?
Or, how to tell GNU radio that this flow/top_block shall run only one time then return?

Any help appreciated, thanks.

**Comment by A1337CBS** [comment]
@Mictronics I had the same issue, so I changed the block to tagged_stream to make it work. I have added a pull request to this project so hopefully you can use it when the pull request is approved or you can get it from my repo. Good luck!

**Comment by Mictronics** [comment]
Thanks, will try.

**Comment by A1337CBS** [comment]
> 
> 
> Thanks, will try.

Great, let us know how it goes

**Comment by Mictronics** [comment]
@A1337CBS Reading into tagged_stream_block make me wonder whether your code is missing an `calculate_output_stream_length` overwrite?

I tried your PR and also modified my project from sync to tagged_stream block. However, I no longer receive any RF output (via hackrf) on a radio scanner nearby. Debugging shows that 32 byte noutput_items are generated in work (from 168 bit input)  when a PDU message is received.

**Comment by Mictronics** [comment]
Half working. With enable_input=false the cyclic RF output is back, with both, yours and my code. RF on sentence message still not working.

**Comment by A1337CBS** [comment]
@Mictronics Its been a while since I looked at the code but will look at up when I have time. I am confused though, can you let me know what are you trying to do and post a screenshot of your flowgraph?

**Comment by Mictronics** [comment]
@A1337CBS Porting stuff to GR3.8 and Python3 to avoid any hassle in future. Started with a new module from scratch. I'm on the way, stay tuned, I will report back. Steep learning curve btw, I like that.

**Comment by Mictronics** [comment]
First working code, more to come. https://github.com/Mictronics/ais-simulator
Issue solved.
