### ISSUE TITLE
Installing AIS TX

### ISSUE THREAD

**Issue by Teles18** [trendmicro/ais#7]
Hi, 
When I do the (cmake ../) this comes up:
 -- Build type not specified: defaulting to release.
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   filesystem
--   system
CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 44

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:25 (include)
  swig/CMakeLists.txt:28 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 92

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:25 (include)
  swig/CMakeLists.txt:28 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 100

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:25 (include)
  swig/CMakeLists.txt:28 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at cmake/Modules/GrPython.cmake:103 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:25 (include)
  swig/CMakeLists.txt:28 (include)

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 44

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  swig/CMakeLists.txt:29 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 92

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  swig/CMakeLists.txt:29 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 100

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  swig/CMakeLists.txt:29 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at /usr/share/cmake-3.12/Modules/UseSWIG.cmake:492 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:158 (SWIG_ADD_MODULE)
  swig/CMakeLists.txt:42 (GR_SWIG_MAKE)

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 44

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:182 (include)
  swig/CMakeLists.txt:47 (GR_SWIG_INSTALL)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 92

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:182 (include)
  swig/CMakeLists.txt:47 (GR_SWIG_INSTALL)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 100

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  cmake/Modules/GrSwig.cmake:182 (include)
  swig/CMakeLists.txt:47 (GR_SWIG_INSTALL)
This warning is for project developers.  Use -Wno-dev to suppress it.

Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 44

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  python/CMakeLists.txt:23 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 92

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  python/CMakeLists.txt:23 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 100

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  python/CMakeLists.txt:23 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at cmake/Modules/GrPython.cmake:103 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  python/CMakeLists.txt:23 (include)

Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at cmake/Modules/GrPython.cmake:115 (add_custom_target):
  add_custom_target cannot create target "ALL" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory "/home/diogo/ais/gr-aistx/swig".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/GrPython.cmake:214 (GR_UNIQUE_TARGET)
  python/CMakeLists.txt:31 (GR_PYTHON_INSTALL)

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 44

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  apps/CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 92

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  apps/CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrPython.cmake:196:
  Syntax Warning in cmake code at column 100

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  apps/CMakeLists.txt:20 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

  File "<string>", line 3
    print sysconfig.get_python_lib(plat_specific=True, prefix='')
                  ^
SyntaxError: invalid syntax
CMake Error at cmake/Modules/GrPython.cmake:103 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  apps/CMakeLists.txt:20 (include)

Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at cmake/Modules/GrPython.cmake:115 (add_custom_target):
  add_custom_target cannot create target "ALL" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory "/home/diogo/ais/gr-aistx/swig".  See
  documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  cmake/Modules/GrPython.cmake:214 (GR_UNIQUE_TARGET)
  apps/CMakeLists.txt:22 (GR_PYTHON_INSTALL)

-- Configuring incomplete, errors occurred!
See also "/home/diogo/ais/gr-aistx/build/CMakeFiles/CMakeOutput.log".

Can someone tell me what's wrong?

Thanks

**Comment by ghost** [comment]
Hi Teles18,

Could you tell me what version you are using? As best I can tell trendmicro has no intention of maintaining this and as such there are multiple pull requests that are still un-merged. If you are using GNURadio 3.7 or later you will need to use one of those versions.

**Comment by Teles18** [comment]
I'm using GRC 3.7.13.4.

**Comment by ghost** [comment]
You will need to use a version that is compatible with GR 3.7.X dadopap has an open pull request #2 or you can just use my fork here: https://github.com/zhudsonSM/aistx

If you are using pybombs (which i highly recommend) there is also a branch with pybombs compatibility in my repository.

**Comment by Teles18** [comment]
when I clone your version and try to install it I get the same error. I clone that into the home folder and then when I input cmake ../ I get the same error. Sorry if I'm being to "noob" but I'm I doing anything wrong? And if I used pybombs what should I do?
Thanks

**Comment by ghost** [comment]
No worries, we all have to start somewhere and I am no expert on this stuff. Just to confirm you are running "cmake ../" from the build directory: aistx/gr-aistx/build 

If you are and it still isn't working try running "cmake ../ -Wno-dev" to suppress the "extraneous" errors and post what you get here.

You would likely know if you had installed GNURadio with Pybombs but if you want to learn more I would start here: https://www.gnuradio.org/blog/pybombs-the-what-the-how-and-the-why

**Comment by Teles18** [comment]
Yes I'm running cmake ../ from the build directory. The "cmake ../ -Wno-dev" didn't work. 
I'm not sure if I installed it with Pybombs because I installed it a long time ago however I think I did

**Comment by embyte0** [comment]
Please see the comment I made on the other issue: https://github.com/trendmicro/ais/issues/4#issuecomment-444051933

@zhudsonSM I merged your pull request. Is there a way I can contact you, possibly via email for few questions?

Thanks

**Comment by ghost** [comment]
@embyte0 I sent you at your madlab.it address. My email address is zhudson [at] shinemicro.com

**Comment by embyte0** [comment]
Followed up privately via email. I will close this case.

Best

**Comment by hayesrt1234** [comment]
I am late to this branch, and it appears a solution was provided offline from the forum. Would it be possible to provide some insight on this?
