### ISSUE TITLE
Can't send AIS message 

### ISSUE THREAD

**Issue by cvanslyke** [trendmicro/ais#8]
I've been attempting to get this software to work for a couple of weeks now and I can't seem to pick up any messages sent over an AIS receiver. Just wondering if any helpful tips or tricks I should look at because I'm running out of ideas. Here's what I'm running:

- GNURado 3.7.12.0 on Ubuntu 18.04.1. gr-aistx is installed. 
- I've tried transmitting using both the GRC flowgraph (just playing the existing flowgraph), as well as using the AIVDM_Encoder.py script piped into the AiS_TX.py script. 
- I've tried transmitting over a USRP (Ettus X300) as well as a HackRF (I had to update the flowgraph and AiS_TX.py script to switch the sink to an osmocom sink to achieve this).

In all cases, a signal is sent out. I've got a receiver hardwired to my radio and can see some sort of signal coming out at the right frequency. I have a signal recorder that I can use to record/playback signals. If I try to play the signal back, and hook this up to an AIS Receiver (I've tested with both a real Shine Micro AIS receiver as well as using https://github.com/bistromath/gr-ais.git). Neither one seems to be able to pick up the AIS messages being put out. 

I seem to be running into a dead end here. Any help would be greatly appreciated.

**Comment by ghost** [comment]
First let me say that I have not used gr-ais but I have used gr-aistx with a Shine Micro receiver successfully. 

It is hard to say what the problem could be exactly but the first thing I would do is eliminate the actual RF  path and just try putting transmit and receive in the same flow graph. Once you have that working I would verify that your receiver setup is working, try to receive an actual AIS message from a boat nearby. Once you have both of those working my next step would be to compare the demodulated "audio" of the real and generated packets.

Let us know how you get on with that.

**Comment by cvanslyke** [comment]
Thanks for the feedback, it's appreciated. I'll try setting up send/receive in the same flow graph. I'm new to GNURadio and digital signals in general. What should the receive side look like? gr-ais comes with a couple of grc flow graphs but all seem to be missing blocks and I'm not entirely sure what it should look like. I will say that the receive flow graph looks much more complicated than the send provided with this package. 

I have tested the receivers (both the physical receiver as well as the gr-ais one running on my computer) against a Shine Micro AIS Test Box and both are picking up AIS messages. In all cases, I'm not broadcasting/receiving over the air. I've got a hardwired cable connecting all the devices.

**Comment by cvanslyke** [comment]
Ok, I've figured this out. The issue is the HackRF. The minimum suggested samp_rate for the HackRF is 2M. See: https://factorialabs.com/2017/12/14/hackrf-ones-minimum-sample-rate-spec-there-for-a-reason/ 
Once I adjusted the samp_rate up to 2M the flow graph and python script worked without an issue.

**Comment by nazmibojan** [comment]
Hi @cvanslyke,

I need to change UHD sink to osmocom sink like you did before. I managed my osmocom Sink with this setting:

![Screenshot from 2019-11-04 10-39-11](https://user-images.githubusercontent.com/17125575/68098495-9e6b9400-feef-11e9-807a-568d3a48c7ff.png)

But I still can't sent AIS Data although the graph can be executed. Is it something wrong with my setting?
Thanks.

Nazmi

**Comment by ghost** [comment]
The obvious first question is that you have checked that your sample rate is 2M as required by the HackRF. 

Assuming you have that fixed I do not see anything else that would cause a problem. Could you give us a bit more of an explanation of what you are doing, what you expect to happen and what is happening.

**Comment by nazmibojan** [comment]
Hi @zhudsonSM ,
I solved the problem by changing 'Ch0: Frequency' to 162M. My bad.
Thanks

Regards,
Nazmi

**Comment by EinarGaustad** [comment]
Hi @zhudsonSM, 

I'm having a similar problem to @cvanslyke, but rather than having a problem Ettus X300, I'm having a problem with the USRP B200mini where I'm not able to receive any messages generated by the AISTX. 

However, I'm able to obtain actual messages that are sent.  

Any ideas on what the problem could be?

**Edit** I also managed to get it to work with the Hackrf by modifying the flowgraph, but would still like to know why it doesn't work with the USRP

Thanks!

**Comment by denizea** [comment]
Hi @zhudsonSM, @cvanslyke, @nazmibojan and all! :)
I know this is warming up an old topic again, but after many hours of debugging, I am not really able to receive AIS messages.
I am using HackRF One to transmit messages. As @cvanslyke , I both tried Gnu Radio gui and generated python code. On the receive end I am using RTL-SDR and running piece of software called `rtl_ais`. When I go to next to a boat, I am able to receive AIS messages from a transmitter on the boat but when I try to to send ais messages from HackRF, I am not able to receive messages.
I have 2 good marine antennas on both end, and when I transmit, I can see on spectrum analyzer by Universal Radio Hacker something is transmitted on 162 MHz. However, on receive end I can not read the message.
Here are my GNU Radio building blocks.

![gnu-radio](https://user-images.githubusercontent.com/460968/152185567-f581d67e-11a4-4f1d-80a6-cab34f7b59d1.png)
![osmocom-sink](https://user-images.githubusercontent.com/460968/152185572-15a55c12-fce6-494e-ab72-905080b37a46.png)


Do you have any idea, what could be wrong? Huge thanks!
